version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dr-yum-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: yum_admin
      POSTGRES_PASSWORD: yum_password
      POSTGRES_DB: dryum
    volumes:
      - ./pgdata_final:/var/lib/postgresql/data